softwareengineering-2024-2/softwareengineering-repo

- app.py
- views/project_view.py
> ex) #8
> 디렉토리 구조에 맞게 폴더 생성 후 temp 파일을 생성
> project_view.py 추가 후 app.py에서 project_view import하는 코드 작성
> Feature issue #8: 디렉토리 구조 및 app.py 생성

- .gitignore
- app.py
- controllers/auth.py
- templates/index.html
> ex) #11 로그인 기능 구현
> app.py와 auth.py 구별
> .env 파일 분리
> oauth 토큰 발급
> 구글 로그인 성공시 이름과 프로필 사진 띄어주는 기능 작동 확인
>
> 로그인 기능 기본 구현

- .gitignore
- app.py
- controllers/auth.py
- controllers/create_project.py
- controllers/profile.py
- controllers/project_main.py
- templates/create_project.html
- templates/index.html
- templates/profile.html
- templates/project_main.html
> #14 프로젝트 생성, 프로필 수정 기능 
> 로그인 완료 후 프로젝트 생성하는 기능, 프로필 수정하는 기능 간단하게 연습할 겸 구현해봤어요
아직 DB 구축 전이라서 프로젝트는 1개만 생성할 수 있게 했습니다(추후 여러 개 생성할 수 있게 수정할 것)
profile.py, profile.html -> 프로필 수정
create_project.py, create_project.html -> 프로젝트 생성
project_main.py, project_main.html -> 프로젝트 생성 후 프로젝트 메인
커밋 메시지 타입을 test로 잘못 넣어버렸어요...
> feat: 프로젝트 생성, 프로필 수정 기능

- app.py
> feat: DB 연결 변경

- app.py
- controllers/sprint_controller.py
- models/sprint_model.py
- templates/project_main_back.html
- templates/sprint_back.html
- views/sprint_view.py
> ex) #25
> 스프린트, 스프린트 백로그 CRUD 구현
<스프린트 생성>
<스프린트 목록, 수정, 삭제>
<스프린트 백로그 목록, 수정, 삭제>
> 스프린트 기능 구현

- static/icons/checkbox-off.svg
- static/icons/checkbox.svg
- static/js/manage_project.js
- static/js/milestone.js
- static/milestone.css
- templates/manage_project.html
- templates/milestone.html
> ex) #43, #26
> 마일스톤 페이지 레이아웃 구현(수직선 제외),
> project_manage.html에서 프로젝트 참여 모달이 제대로 작동하지 않던 부분 수정
> project_manage.html 부분 모달 일부 구조 수정
> 마일스톤 페이지 수직선 부분 기능 추가를 부탁드립니다 ... (제 실력 이슈)
> feat issue #43, #26 마일스톤 페이지, 프로젝트 참여 모달 js 수정

- static/js/milestone.js
- static/milestone.css
- templates/milestone.html
>#43
> 마일스톤 수직선 작업
-- 해당 마일스톤 값은 milestone.js 안에 포함
> feat: 마일스톤 수직선 작업 완료

- controllers/productbacklog_controller.py
- templates/productbacklog_back.html
- views/productbacklog_view.py
> ex) #36, #49 
> productbacklog_controller.py, productbacklog_view.py, productbacklog_back.html 파일의 디버그 코드를 삭제하고, 코드 작동 시 필요하지 않은 주석, 코드를 삭제 및 수정했습니다.
> feat issue #36, #49: 프로덕트 백로그 디버그 코드 삭제

- controllers/sprint_controller.py
- static/js/sprint.js
- templates/sprint.html
- views/sprint_view.py
> refactor: 스프린트 페이지 기능 수정

- app.py
- controllers/auth.py
- controllers/project_controller.py
- static/login.css
- templates/join_project.html
- templates/login.html
- templates/manage_project.html
- templates/profile.html
- templates/topbar.html
- views/manage_project_view.py
> ex) #53
> 로그인 및 프로젝트 관리 기능 프론트 백 연결
* 프로필 기능 연결 아직 안 됨
> feat issue #53: 로그인 및 프로젝트 관리 기능 프론트 백 연결

- templates/sprint.html
> fix: 스프린트 생성시 프로덕트 백로그 선택 오류 수정

- static/backlog.css
- static/icons/backlog_background.svg
- static/js/backlog.js
- templates/backlog.html
- views/productbacklog_view.py
> #46 
> 프로덕트 백로그 페이지 html, css 구현
-  input box가 드래그 되는 현상을 수정하였습니다.
- productbacklolg_view 파일에서 backlog.html로 렌더링되게 수정하였습니다.
- 유저스토리 목록 타이틀이 드래그 되는 현상 수정
- 백로그 목록에서 백로그 삭제 시 유저스토리가 삭제되고 새로고침해야지 나타나는 부분을 유저스토리가 바로 나타나도록 수정하였습니다.
> @dudcoco 기존 backlog js부분을 backlog.js 파일로 따로 분리하였습니다! div구조 수정하면서 js 코드를 일부 수정하였습니다.
> feat issie #46 : 프로덕트백로그 레이아웃 구현

- static/manage_project.css
- static/profile.css
- templates/join_project.html
- templates/manage_project.html
- templates/profile.html
- templates/project_created_back.html
> fix issue #64: profile, 참여 링크, manga_project css 수정

- static/manage_project.css
- templates/join_project.html
- templates/milestone.html
> refactor #64: 마일스톤 수정기능 삭제

- controllers/sprint_controller.py
- templates/main.html
- views/project_main_view.py
> feat: 메인 페이지 스프린트 인자 추가

- static/js/backlog.js
> ex) #65 
>  프로덕트 백로그 페이지를 연결하고, backlog.js 파일을 수정하여 백로그 삭제/저장이 되지 않는 문제를 해결했습니다.
> feat issue #65: backlog.js 에러 수정

- static/js/sprint.js
- static/sprint.css
- static/topbar.css
- templates/sprint.html
> #58-style/전체적인-css-수정
>css 수정 및
> sprint 이동 화살표 수정
> feat: css 수정 및 sprint 화살표 수정

- controllers/sprint_controller.py
- static/sprint.css
- views/sprint_view.py
> refactor: 스프린트 날짜 중복 문제 해결

- static/js/sprint.js
- static/sprint.css
- templates/sprint.html
> feat: sprint 모달수정 밑 프론트에서 금지항목 검사

- static/js/milestone.js
> feat issue #61: 마일스톤 수직선 기능 수정

- static/backlog.css
- static/main.css
- templates/main.html
> ex) #77
> main.html, backlog css 수정
> refactor issue #77: main.html, backlog css 수정

- controllers/userstory_controller.py
- static/js/userstory.js
- static/userstory.css
- templates/userstory.html
- views/userstory_view.py
> #74 
> 예전 css 삭제
> 키워드 삭제시 성공알림
> 유저스토리 프로덕트 백로그에서 사용중일때 수정 불가
> feat issue #74: not 리스트 키워드 감지

- static/js/profile.js
> #83 
> 프로필 수정 에서 역할 선택시 드롭박스 꺼짐
> feat issue #83: 프로필 설정창 기능 추가

- controllers/project_controller.py
- templates/manage_project.html
- templates/profile.html
- templates/userstory.html
> ex) #85
> 프로필 화면의 역할 선택창에 현재 역할 표시 -> 처음 설정하는 경우 'Member'로 설정됨
> 유저스토리 화면의 not list 입력창 문구의 오타 수정
> refactor issue #86: 프로필 역할 선택창 수정 및 유저스토리 오타 수정

- controllers/auth.py
- templates/sprint.html
- templates/topbar.html
- views/sprint_view.py
- views/userstory_view.py
> #87
> 로그인이 되지 않은 상태일 경우 처음 화면을 렌더링하도록 수정
> 로그아웃 시 세션에서 토큰을 제거하도록 수정
> notlist 삭제 시 삭제 확인 모달창이 한 번만 뜨도록 수정
> 스프린트 생성 및 수정 시 프로덕트 백로그를 여러 개 선택하고 submit을 할 때 발생하는 오류 해결
> bugfix issue #87: 로그인 로직 수정, notlist 삭제 모달창 오류 해결, 스프린트에서 백로그 다중 선택 문제 해결

- controllers/alert_controller.py
- models/alert_model.py
- static/js/topbar.js
- static/js/userstory.js
- templates/topbar.html
- templates/userstory.html
- views/userstory_view.py
> ex) #23 NOT 리스트 키워드 포함 유저스토리 작성시 알림 보이기 기능
> not 리스트에 포함되는 키워드를 작성하면 pm에게 알림이 뜹니다.
> 최대 5개가 뜹니다.
> 팀원인 경우 알림이 뜨지 않습니다.
>다른 파일의 코드들이 최신의 상태가 맞는지 확인해주세요..
> 브랜치가 제대로 된건지 잘 모르겠어요.
> #23 NOT 리스트 키워드 포함 유저스토리 작성시 알림 보이기 기능

- controllers/alert_controller.py
- controllers/todolist_controller.py
- models/alert_model.py
- models/todolist_model.py
- static/js/main.js
- static/js/userstory.js
- templates/main.html
- views/project_main_view.py
- views/userstory_view.py
>  #92 , #23 
> 투두리스트 작성
> 투두리스트 수정
> 투두리스트 완료 상태 변경
> 투두리스트 삭제
> alert 테이블 변경
>
> #92 feat/투두리스트 기능 구현

- static/js/retrospect.js
- static/retrospect.css
- templates/retrospect.html
> #97
> 회고관리 관리페이지 넘기는 부분위치 수정
> 회고 하나도 없을때 추가
> 삭제 확인 모달 추가
> 수정 삭제 권한에 따라 달라지도록
> #97 feat/프론트 회고 페이지 생성

- controllers/retrospect_controller.py
- drive/drive_init.py
> ex) #90, #107 
> file_link에 파일 다운로드 링크를 저장하도록 수정했습니다
> feat issue #90: 파일 다운로드 링크를 저장하도록 기능 수정

- static/calender.css
- static/icons/nav-arrow-left.svg
- static/icons/nav-arrow-right.svg
- static/js/calender.js
- templates/calendar_back.html
- templates/create_schedule_back.html
- views/calendar_view.py
> ex) #96 
> 캘린더 프론트엔드 구현, 일정 추가까지는 가능
> 일정 삭제와 수정 구현 필요
> feat issue#96: 캘린더 프론트엔드 구현

- controllers/calendar_controller.py
- controllers/todolist_controller.py
- models/calendar_model.py
- static/js/calender.js
- templates/calendar_back.html
- templates/create_schedule_back.html
- views/calendar_view.py
- views/milestone_view.py
- views/sprint_view.py
> ex) #116 
> 캘린더 화면에서 일정을 볼 수 있다.
> 캘린더 화면에서 일정을 추가할 수 있다.
> 일정을 수정 / 삭제할 수 있다.
> 팀별 / 개인 일정 필터링이 가능하
다른 유저면 다른 유저의 일정을 보지 못하게 했음.
> feat 116  : 캘린더 일정 조회 수정 삭제

- drive/drive_init.py
- templates/create_retrospect.html
- templates/view_retrospect.html
- views/retrospect_view.py
> ex) #90, #111 
> 회고 조회 시 첨부한 파일의 이름이 보이도록 구현했습니다.
> feat issue #90: 회고 조회 시 파일 이름 보이도록 구현

- static/calender.css
- static/js/calender.js
- static/js/main.js
- static/js/manage_project.js
- static/main.css
- static/manage_project.css
- static/scrum.css
- static/sprint.css
- templates/calendar_back.html
- templates/main.html
- templates/manage_project.html
- templates/scrum.html
- templates/sprint.html
> ex) #119
> 캘린더 페이지 css 수정
- 상세 모달 수정
- 일정 추가 버튼 수정
> 스크럼 페이지 css 수정
- 작업율 바가 제대로 안뜨는 부분 수정
- 상태 저장 버튼 css 수정
> 메인 페이지 css 수정
- 프로그레스바 배경 색이 흰색으로 되어있는 부분 -> 회색 수정
- 2주 캘린더 뼈대 추가
- 2주 캘린더 섹션 전체에 onclick이 있는 경우 날짜가 제대로 불러와지지 않아 2주 캘린더 h2태그에 캘린더페이지로 이동하는 기능 추가함.
> 프로젝트 페이지 기능 추가
- 프로젝트 나가기 버튼 클릭 시 확인 모달 띄우기
> 2주 캘린더 부분 이해 안되면 물어봐주세용
> html&css #119: htmlcss 캘린더 스크럼 html css 수정

- controllers/calendar_controller.py
- models/calendar_model.py
- models/sprint_model.py
- views/milestone_view.py
- views/sprint_view.py
> #122
* 마일스톤 연동
> 마일스톤 삭제 시 해당 일정 삭제
* 스프린트 연동
> 스프린트 기간 수정 시 해당 일정 업데이트
> 스프린트 삭제 시 해당 일정 삭제
> feat issue #122: 캘린더 마일스톤/스프린트 연동

- static/backlog.css
- static/js/backlog.js
- static/js/main.js
- static/js/manage_project.js
- static/js/milestone.js
- static/js/sprint.js
- static/js/userstory.js
- static/main.css
- static/manage_project.css
- static/milestone.css
- static/sprint.css
- static/userstory.css
- templates/backlog.html
- templates/milestone.html
- templates/sprint.html
- templates/userstory.html
>#114
> 유저스토리 온보딩, 프로덕트 백로그 온보딩, 스프린트 온보딩
> commit feat issue #114: 온보딩 만들기

- controllers/sprint_controller.py
- static/js/scrum.js
- static/js/sprint.js
- static/js/topbar.js
- static/main.css
- static/scrum.css
- static/topbar.css
- templates/main.html
- templates/scrum.html
- templates/topbar.html
- views/project_main_view.py
- views/scrum_view.py
> #145 
> 스크럼 스프린트 기억
> 스크럼 자동 저장
> 스크럼 온보딩 상태저장 버튼 제거
> topbar 알림 갯수 보이도록 설정
> 메인 페이지 작업목록 정상화
> #145 refactor/코드 리팩토링

- static/js/calender.js
- static/js/main.js
- views/calendar_view.py
> ex) #151 #124 
> 수정할 때 생기는 전반적인 오류 수정
1. 중요가 체크된 일정 색 설정과 관련해서, 색을 지정하지 않으면 오류가 생겼음. 
-> 체크를 풀게 되었을 때 자동으로 주황색으로 하게 바꿈
2. 수정을 여러 번 하게 되었을 때 이전의 수정한 일정에 대해서도 같이 수정이 되는 오류가 있었음
-> 수정 버튼을 누르고 모달이 닫히면 수정 버튼의 이벤트를 없애 해당 스케쥴만 수정되게 함
> 151 캘린더 일정 수정

- static/js/milestone.js
- static/js/scrum.js
- static/milestone.css
- templates/milestone.html
> #145 
> 마일스톤 세부사항 수정
> 스크럼 백로그 우선순위 저장 기능
> refactor issue #145: 코드 리팩토링

- Dockerfile
- static/js/backlog.js
- static/js/burnup.js
- static/js/milestone.js
- static/js/retrospect.js
- static/js/scrum.js
- static/js/sprint.js
- templates/burnup.html
> #172
> 온보딩이 제대로 안뜨고 쿠키만 저장되는 현상 수정
> 온보딩 중 f5를 누르면 정상적으로 실행되도록
> fix issue #172: 온보딩 수정

- .gitignore
- tests/test_guide.py
> 165 test 테스트 케이스 가이드 추가
